### ISSUE TITLE
many errors after fresh installation

### ISSUE THREAD

**Issue by JustDoItSascha** [Ekliptor/WolfBot#25]
Hey,

I very eager to try your trading bot. Unfortunately it's not working. I cloned the project, ran `yarn install` and `yarn add webpack webpack-cli`(because it was missing) and tried to do `yarn watch`, but I get this errors (just an excerpt, I have many more of them):

![image](https://user-images.githubusercontent.com/8389022/63021029-e609f300-be9f-11e9-88fc-40656f6538b7.png)
![image](https://user-images.githubusercontent.com/8389022/63021064-089c0c00-bea0-11e9-8613-e489403a8b3b.png)

**Comment by Ekliptor** [comment]
Hi
My webpack is installed globally, so yes it was missing.

Those errors are mentioned in the readme and can be ignored. They happen due to shared code between client and server which is not in a separate module and needs to be refactored by me. Just ensure `comitOnErrors: true` in the /public/js/tsconfig.json is enbaled (default) and it will still generate client-side code.

Also you only need to run `tsc` in the root folder to make changes to the bot or run it. Running `tsc` in the `/public/js/` is only required if you want to make UI changes
