### ISSUE TITLE
Project images

### ISSUE THREAD

**Issue by maurodelazeri** [Ekliptor/WolfBot#4]
It would be nice here or on the website to have some images from the web interface, I notice you are using the tradingview with socket, really excited to see the results.... I have a lot of experience with data feed (fix/socket), any help you need, let me know

**Comment by Ekliptor** [comment]
Hey. Thanks for your offer.
The TradingView chart is already fully integrated.
What still needs to be done here is:

- integrating manual orders via TV broker API to show them on chart
- show more strategy infos on the chart (instead of just below)

Also the UI in general will probably improve a lot over the next few months. I posted some screenshots of it here: https://wolfbot.org/50-early-access-discount/

If you have experience in UI development or are a trader with TypeScript coding experience feel free to contact me via Github or wolfbot.org
The good thing about a mixed open source & paid software is that there will always be paid work for developers who are active in the project and commit important features.

**Comment by Ekliptor** [comment]
closing it for now. Feel free to open new issues if you have more specific questions
